export const dataKeysArray = [
    "sfp_id",
    "uam_id",
    "device_name",
    "status",
    "serial_number",
    "media_type",
    "port_name",
    "port_type",
    "connector",
    "mode",
    "speed",
    "wavelength",
    "optical_direction_type",
    "pn_code",
    "eos_date",
    "eol_date",
    "rfs_date",
    "creation_date",
    "modification_date",
  ];
  