export const generateFltersList = ({
  onSiteChange,
  siteChangeLoader,
  onInlineFieldChange = () => {},
  selectedIpAddress,
  setSelectedIpAddress,
  selectedDeviceName,
  setSelectedDeviceName,
  selectedDeviceType,
  setSelectedDeviceType,
  selectedDeviceScorePoint,
  setSelectedDeviceScorePoint,
  softwareVersion,
  hardwareVersion,
  siteNames,
  vendors,
  deviceTypes,
  racks,
}) => ({
  inlineFilters: [
    {
      name: 'ip_address',
      type: 'input',
      //   value: selectedIpAddress,
      onChange: onInlineFieldChange,
      placeholder: 'IP Address',
    },
    {
      name: 'device_name',
      type: 'input',
      //   value: selectedDeviceName,
      onChange: onInlineFieldChange,
      placeholder: 'Device Name',
    },
    {
      name: 'device_type',
      type: 'select',
      options: deviceTypes,
      //   value: selectedDeviceType,
      onChange: onInlineFieldChange,
      placeholder: 'Select Device Type',
    },
    {
      name: 'score',
      type: 'select',
      options: [
        { label: 'greater than 8', value: '8' },
        { label: '5-8', value: '5-8' },
        { label: '0-5', value: '0-5' },
      ],
      //   value: selectedDeviceScorePoint,
      onChange: onInlineFieldChange,
      placeholder: 'Select Score Point',
      filterstyle: {
        width: '300px',
      },
    },
  ],

  // console.log("");

  advanceFilters: [
    {
      name: 'ip_address',
      type: 'input',
      value: selectedIpAddress,
      placeholder: 'IP Address',
    },
    {
      name: 'device_name',
      type: 'input',
      value: selectedDeviceName,
      placeholder: 'Device Name',
    },
    {
      name: 'device_type',
      type: 'select',
      options: deviceTypes,
      value: selectedDeviceType,
      placeholder: 'Select Device Type',
    },
    {
      name: 'score',
      type: 'select',
      options: [
        { label: 'greater than 8', value: '8' },
        { label: '5-8', value: '5-8' },
        { label: '0-5', value: '0-5' },
      ],
      value: selectedDeviceScorePoint,
      placeholder: 'Score Point',
      filterstyle: {
        width: '300px',
      },
    },
    {
      name: 'serial_no',
      type: 'input',
      placeholder: 'Serial No',
    },
    {
      name: 'site_id',
      type: 'select',
      options: siteNames,
      value: '',
      placeholder: 'Site',
      onChange: onSiteChange,
    },
    {
      name: 'rack_id',
      type: 'select',
      options: racks,
      //   onClear: onRackClear,
      loader: siteChangeLoader,
      placeholder: 'Rack',
    },
    {
      name: 'vendor_id',
      type: 'select',
      options: vendors,
      value: '',
      placeholder: 'Vendor',
    },
    {
      name: 'model_no',
      type: 'input',
      value: '',
      placeholder: 'Model No',
    },
    {
      name: 'department',
      type: 'input',
      value: '',
      placeholder: 'Department',
    },
    {
      name: 'sntc_date',
      type: 'date',
      value: '',
      placeholder: 'SNTC Date',
    },
    {
      name: 'hardware_version',
      type: 'select',
      options: hardwareVersion,
      value: '',
      placeholder: 'Hardware Version',
    },
    {
      name: 'software_version',
      type: 'select',
      options: softwareVersion,
      value: '',
      placeholder: 'Software Version',
    },
  ],
});
