export const dataKeysArray = [
    "subboard_name",
    "device_name",
    "serial_number",
    "status",
    "pn_code",
    "subboard_type",
    "subrack_id",
    "slot_number",
    "subslot_number",
    "device_slot_number",
    "software_version",
    "hardware_version",
    "manufacturer_date",
    "eos_date",
    "eol_date", 
    "creation_date", 
    "modification_date", 
  ];
  